# config/storage.yml
cloudinary:
  service: Cloudinary
  folder: <%= Rails.env %>

# config/environments/development.rb
config.active_storage.service = :cloudinary

# config/environments/production.rb
config.active_storage.service = :cloudinary
